remote_theme: "mmistakes/minimal-mistakes@4.15.2"

plugins:
  - jekyll-include-cache

# Site Settings
locale                   : "en-US"
title                    : "MagneTag Documentation"
title_separator          : "-"
name                     : "MagneTag, LLC"
description              : # "An amazing website."
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/icon_with_text.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title

defaults:
  - scope:
      path: ""
    values:
      sidebar:
        nav: "docs"
      layout: "single"
